version: '3'
services:
  app:
    build: .
    volumes:
      - .:/opt/webapp
      - public-data:/opt/webapp/public
      - tmp-data:/opt/webapp/tmp
      - log-data:/opt/webapp/log
    command: bash -c "rm -f tmp/pids/server.pid && rake db:migrate && bundle exec unicorn -p 3000 -c config/unicorn.rb"
    depends_on:
      - db
      - redis
    tty: true
    stdin_open: true
    env_file: containers/rails/.env
  db:
    restart:
      always
    image: mysql:5.7.22
    environment:
      - MYSQL_ROOT_PASSWORD=toor
    volumes:
      - ./containers/mysql/my.cnf:/etc/mysql/my.cnf
      - db-data:/var/lib/mysql
    ports:
      - 43306:3306
  web:
    build:
      context: containers/nginx
    volumes:
      - public-data:/opt/webapp/public
      - tmp-data:/opt/webapp/tmp
    ports:
      - 80:80
    depends_on:
      - app
  redis:
    image: redis:3.2.4-alpine
    ports:
      - 46379:6379
  mail:
    image: schickling/mailcatcher
    ports:
      - 41080:1080
      - 41025:1025
volumes:
  public-data:
  tmp-data:
  log-data:
  db-data:
